# This task avoids downloading cloudwatch-agent every time
- name: RedHat | Check if cloudwatch-agent is present
  command: "/usr/bin/amazon-cloudwatch-agent-ctl -h"
  register: cloudwatch_agent_installed
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: Amazonlinux | Override ansible fact
  set_fact:
    ansible_distribution: amazon_linux
  when: ansible_distribution == "Amazon"

- name: RedHat | Install cloudwatch agent
  yum:
    name: "https://s3.amazonaws.com/amazoncloudwatch-agent/{{ ansible_distribution|lower }}/amd64/latest/amazon-cloudwatch-agent.rpm"
    state: present
  when: cloudwatch_agent_installed.rc != 0

- name: RedHat | Cloudwatch agent service
  service:
    name: amazon-cloudwatch-agent
    state: started
    enabled: yes
