name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  test:
    name: ${{ matrix.distribution }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - ansible-centos:8
          - ansible-centos:7
          - ansible-centos:6
          - ansible-ubuntu:20.04
          - ansible-ubuntu:18.04
          - ansible-ubuntu:16.04
          - ansible-debian:10
          - ansible-debian:9
          - ansible-debian:8
          - ansible-oraclelinux:8
          - ansible-oraclelinux:7
          - ansible-oraclelinux:6
          - ansible-amazonlinux:2
          - ansible-amazonlinux:1
          - ansible-opensuse:15.1
          - ansible-opensuse:15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.18.51

      - name: Test Ansible role amazon-cloudwatch
        run: |
          container_id=$(mktemp)

          # Run container and mount ansible role with it
          sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-amazon-cloudwatch:ro diodonfrost/${{ matrix.distribution }} > "${container_id}"

          # Check syntax
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-amazon-cloudwatch/tests/test.yml --syntax-check

          # Run ansible playbook
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-amazon-cloudwatch/tests/test.yml

          # Test indempotence
          sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-amazon-cloudwatch/tests/test.yml \
          | grep -q 'changed=0.*failed=0' \
          && (echo 'Idempotence test: pass' && exit 0) \
          || (echo 'Idempotence test: fail' && exit 1)

          # Test role
          inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})
